# Generated by Django 5.2.13 on 2026-04-26 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('poetry', 'poesia'), ('painting', 'pintura'), ('sculpture', 'escultura'), ('music', 'música'), ('dance', 'dança'), ('theater', 'teatre'), ('ceramics', 'ceràmica'), ('photography', 'fotografia'), ('literature', 'literatura'), ('cinema', 'cinema'), ('cooking', 'cuina'), ('comics', 'còmic'), ('fashion', 'moda'), ('crafts', 'manualitats'), ('design', 'disseny'), ('technology', 'tecnologia'), ('writing', 'escriptura'), ('sports', 'esports'), ('gaming', 'jocs'), ('other', 'altres')], max_length=50)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments', to='api.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esdeveniments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
